apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: financeservice
  name: financeservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: financeservice
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: financeservice
    spec:
      containers:
        - env:
            - name: DB_SERVER
              value: postgresqldb-finance
            - name: POSTGRES_DB
              value: financeservice
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          image: bogdannaida/finance-service:latest
          imagePullPolicy: ""
          name: finance-service
          ports:
            - containerPort: 8085
          resources: { }
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: postgres-data-finance
          persistentVolumeClaim:
            claimName: postgres-data-finance
status: { }